### PR TITLE
Second version of LU factorization

### PR DESCRIPTION
**Pull request by dan-free**
This has the version of the LU factorization page I was in the process of creating when I learned that Spencer had already pushed a version (see emails previously). In case it is helpful, I'm sending this to you, but if it is not helpful, I'm not offended if you don't use it. The other request I sent has the engineering example from here and then all of Spencer's work

### CODE REVIEW

**Comment by randybeard** [comment]
Dan:  Please rename the file to "tt17_lu_factorization2.ipynb and submit another pull requests.  I'll just include both files.

**Comment by dan-free** [comment]
Ok, I changed the filename. Let me know of anything else I can do. Sorry this was a bit of a headache for you!

**Comment by randybeard** [comment]
Can you do another pull request?  Thanks!

On December 10, 2020 at 9:07:34 PM, Daniel Free (notifications@github.com) wrote:

Ok, I changed the filename. Let me know of anything else I can do. Sorry this was a bit of a headache for you!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

—
Randal W. Beard
Professor, Electrical and Computer Engineering
Brigham Young University
(801) 422-8392, beard@byu.edu

**Comment by dan-free** [comment]
Going to send the pull request again as per Dr. Beard

**Pull request closed without merging**
